[parity]
chain = "chain-spec.json"
base_path = "/tmp/parity2"
[network]
id = 0x2323
reserved_only = true
reserved_peers = "myPrivateNetwork.txt"
port = 30302
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["https://remix-alpha.ethereum.org"]
# [ui]
# port = 8181
[websockets]
port = 8452
[misc]
log_file = "/tmp/parity2.log"
# logging = "debug"
[ipc]
disable = true
[account]
password = ["node2.pwd"]
[mining]
engine_signer = "0x508010ed0c32326b1ea85e33a991834af3df0f15"
# force_sealing = true
reseal_on_txs = "none"
# refuse_service_transactions = false
usd_per_tx = "0"