[parity]
chain = "chain-spec.json"
base_path = "/tmp/parity0"
[network]
id = 0x2323
reserved_only = true
reserved_peers = "myPrivateNetwork.txt"
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["https://remix-alpha.ethereum.org"]
# [ui]
# port = 8180
[websockets]
port = 8450
[misc]
log_file = "/tmp/parity0.log"
# logging = "debug"
[account]
password = ["node0.pwd"]
[mining]
engine_signer = "0x7d58a45837cc637a94c3ff7c98116861343595ff"
# force_sealing = true
reseal_on_txs = "none"
# refuse_service_transactions = false
usd_per_tx = "0"